### ISSUE TITLE
랜딩 페이지 -> 스토리 페이지 확인

### ISSUE THREAD

**Issue by minusmo** [GDSC-CAU/Carbon-Hero#25]

**Comment by Jwaminju** [comment]
carbon hero 라는 제목 및 LinkToNext 버튼에 원래 글씨가 있었던거 같은데,, 제가 합치면서 깨뜨린 걸까용?? 
![Image](https://user-images.githubusercontent.com/49024958/226654127-74f6c45a-420a-43d5-b4bd-d03d6baddfbc.png)

**Comment by minusmo** [comment]
텍스트가 있는데 검은색이라 안보이는 것 같네요
