### ISSUE TITLE
story page 개발

### ISSUE THREAD

**Issue by minusmo** [GDSC-CAU/Carbon-Hero#6]

**Comment by Jwaminju** [comment]
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/49024958/224523338-117f9593-b503-480d-8f73-b23bb3c1ecce.png">
현재까지 구현한 페이지 모양입니다! 보시고 피드백 있으시면 부탁드려요~

**Comment by minusmo** [comment]
@Jwaminju 민주님이 개발하신(지난 회의 때 보여주신) 스토리 페이지가 현재 dev 브랜치에 병합되어있지 않은 상태인가요?
